language: node_js
os:
  - linux
node_js:
  - node
script:
  - npm install
  - npm run lint
  - npm run deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_f009e2359ef0_key -iv $encrypted_f009e2359ef0_iv
    -in deploykey.enc -out deploykey -d
