language: node_js
os:
  - linux
node_js:
  - node
script:
  - npm install
  - npm run lint
  - npm run build
  - chmod +x ./.travis-deploy.sh
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: ./.travis-deploy.sh
    on:
      branch: master
